CC := clang++
CFLAGS := -std=c++2a -Werror -Ofast -Wabstract-vbase-init -Wall -Wextra -Walloca -Wpedantic -Wunused -Wanon-enum-enum-conversion -Warc-repeated-use-of-weak -Warray-bounds-pointer-arithmetic -Wassign-enum -Watomic-implicit-seq-cst -Watomic-properties -Wauto-import -Wbad-function-cast -Wbinary-literal -Wbind-to-temporary-copy -Wbitfield-enum-conversion -Wbitwise-op-parentheses -Wbool-operation -Wcalled-once-parameter -Wcast-align -Wcast-function-type -Wcast-qual -Wchar-subscripts -Wclass-varargs -Wcomma -Wcomment -Wcompletion-handler -Wcomplex-component-init -Wcompound-token-split -Wconditional-uninitialized -Wconsumed -Wconversion -Wcovered-switch-default -Wcustom-atomic-properties -Wdate-time -Wdelete-non-abstract-non-virtual-dtor -Wdelete-non-virtual-dtor -Wdeprecated -Wdirect-ivar-access -Wdisabled-macro-expansion -Wdocumentation -Wdocumentation-pedantic -Wdocumentation-unknown-command -Wdollar-in-identifier-extension -Wdtor-name -Wduplicate-decl-specifier -Wduplicate-enum -Wduplicate-method-arg -Wduplicate-method-match -Wdynamic-exception-spec -Wembedded-directive -Wempty-init-stmt -Wendif-labels -Wenum-conversion -Wenum-too-large -Wexport-unnamed -Wextra-semi -Wfloat-conversion -Wfloat-equal -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-nonliteral -Wformat-pedantic -Wformat-type-confusion -Wframe-address -Wgcc-compat -Wglobal-constructors -Wgnu -Wheader-hygiene -Widiomatic-parentheses -Wimplicit -Wimplicit-atomic-properties -Wimplicit-fallthrough -Wimplicit-float-conversion -Wimplicit-function-declaration -Wimplicit-int -Wimplicit-int-conversion -Wimplicit-int-float-conversion -Wimplicitly-unsigned-literal -Wincomplete-module -Winconsistent-missing-destructor-override -Winfinite-recursion -Wint-in-bool-context -Winvalid-or-nonexistent-directory -Wkeyword-macro -Wlanguage-extension-token -Wlocal-type-template-args -Wlogical-op-parentheses -Wmain -Wmethod-signatures -Wmicrosoft -Wmisleading-indentation -Wmismatched-tags -Wmissing-braces -Wmissing-field-initializers -Wmissing-method-return-type -Wmissing-noreturn -Wmost -Wmove -Wnested-anon-types -Wnewline-eof -Wnon-virtual-dtor -Wnull-pointer-arithmetic -Wnull-pointer-subtraction -Wold-style-cast -Woverlength-strings -Woverloaded-virtual -Wparentheses -Wpointer-arith -Wreserved-user-defined-literal -Wself-assign -Wshorten-64-to-32 -Wsign-compare -Wsign-conversion -Wsometimes-uninitialized -Wstring-concatenation -Wstring-conversion -Wsuggest-destructor-override -Wsuggest-override -Wswitch-enum -Wtautological-compare -Wthread-safety -Wtype-limits -Wundefined-reinterpret-cast -Wuninitialized -Wunknown-pragmas -Wunreachable-code-aggressive -Wused-but-marked-unused -Wvector-conversion -Wzero-as-null-pointer-constant -Wfatal-errors -funroll-loops -finline-functions -fno-builtin
TARGET := bigint-exp-evaluator

SRCS := $(wildcard *.cpp)
OBJS := $(patsubst %.cpp,%.o,$(SRCS))

all: clean
clean: $(TARGET)
	rm -rf *.o
$(TARGET): $(OBJS)
	$(CC) -o $@ $^
%.o: %.cpp
	$(CC) $(CFLAGS) -c $<
